version: '3.9'

services:
  api:
    build:
      context: api-gen-barcode
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DOCKER_CONTENT_TRUST=1
      - APP_RUNTIME_NAME=api-gen-barcode
      - RUNTIME_BUILD=/opt/build/

  frontend:
    build:
      context: frontend-gen-barcode
      dockerfile: Dockerfile
    ports:
      - "80:80"
